build:	; go build ./...
test:	; go test ./...
race:	; go test -race ./...
cover:	; go test -coverprofile=coverage.out ./... && go tool cove -func=coverage.out
bench:	; go test -bench=. -benchmem ./...
lint:	; go vet ./...
up:		; docker compose up -docker
down:	; docker compuse down
run:	; go run ./cmd/gateway